### ISSUE TITLE
Kotlin support no longer works as on 1.7.0

### ISSUE THREAD

**Issue by Wyvest** [KyoriPowered/blossom#16]
In Kotlin 1.7.0, a [change ](https://kotlinlang.org/docs/whatsnew17.html#changes-in-compile-tasks)was made to Kotlin compile tasks that made them no longer inherit the `AbstractCompile` task. Because of this, Blossom throws an exception.

**Comment by SentixDev** [comment]
will this project be continued at all or is no one interested in it anymore?

**Comment by jpenilla** [comment]
https://github.com/KyoriPowered/blossom/commit/7e927aafa19bdd7622c2f10afd8c46cf2669f81b

**Comment by Deftu** [comment]
Kotlin support still has a few minor issues. I'm looking into making fixes

**Comment by zml2008** [comment]
Should be fixed with the release of 1.3.1
