### ISSUE TITLE
Update from 1.2.0 to 1.3.0 breaks kotlin project.

### ISSUE THREAD

**Issue by Im-Fran** [KyoriPowered/blossom#17]
I was using version 1.2.0 and everything worked, but updating to 1.3.0 will always throw this error:
> The task 'compileKotlin' (org.jetbrains.kotlin.gradle.tasks.KotlinCompile) is not a subclass of the given type (org.gradle.api.tasks.compile.AbstractCompile).

- Example repository: [TheProgramSrc/SimpleCore-FilesModule](https://github.com/TheProgramSrc/SimpleCore-FilesModule)
- Code with v1.3.0: [Pull Request in TheProgramSrc/SimpleCore-FilesModule](https://github.com/TheProgramSrc/SimpleCore-FilesModule/pull/14)

I tested it in my local machine, the only difference is the use of v1.3.0 of blossom.

**Comment by jpenilla** [comment]
related to #16

**Comment by Im-Fran** [comment]
Oh, thanks for the info. I'll close it then :p
