### ISSUE TITLE
Source files created by annotation processor aren't compiled into class files

### ISSUE THREAD

**Issue by Sunderw3k** [KyoriPowered/blossom#23]
After a day of debugging and trying to use an annotation processor to add source files to my code and getting `NoClassDefFound` I finally noticed that removing the blossom plugin makes the .class file appear. When I add the plugin using 
```
plugins {
    id("net.kyori.blossom") version "1.3.1"
}
```
the file that is supposed to be generated at `./build/classes/java/main/net/sunderw/sunrise/Testlol.class` just doesn't get created.  
The source file created by my processor still exists tho at `./build/generated/source/kapt/main/net/sunderw/Testlol.java`

Kotlin version 1.9.0
Gradle 8.2.1
Using java 1.8 to build and targetting 1.8
Using java 20 for the gradle jvm
Using kapt

**Comment by zml2008** [comment]
Don't use blossom in its current form

**Comment by Sunderw3k** [comment]
What do you mean? Why? Are there any alternatives?
