### ISSUE TITLE
How to avoid separating files with templates to a separate directory?

### ISSUE THREAD

**Issue by AuroraLS3** [KyoriPowered/blossom#35]
Hi.

I see that 2.0.0 changed where templated files are located, or at least the change log suggests so:

>Then place a file in the src/main/resource-templates folder:

I would like to keep the files where they are to not make it confusing to find specific classes like plugin main class.

Is it possible to define specific files for template replacement in the gradle configuration?

**Comment by zml2008** [comment]
no, to fit into the project model that gradle and ides use, templates are a separate source root. put your build-derived constants into a separate class if you'd like to avoid having major regular classes in the templates folder
