### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by lucko** [KyoriPowered/blossom#4]
I've had a quick look, it's not quite as simple (at least I don't think it is) as copy pasting the existing code for Groovy/Scala and making it reference Kotlin instead.

```java
// Groovy
if(this.project.getPlugins().hasPlugin("groovy")) {
  dir = new File(this.project.getBuildDir(), "sources/groovy/");
  final GroovySourceSet set = (GroovySourceSet) new DslObject(main).getConvention().getPlugins().get("groovy");

  task = this.makeTask("blossomSourceReplacementGroovy", SourceReplacementTask.class);
  task.setInput(set.getGroovy());
  task.setOutput(dir);

  final GroovyCompile compile = (GroovyCompile) this.project.getTasks().getByName(main.getCompileTaskName("groovy"));
  compile.dependsOn("blossomSourceReplacementGroovy");
  compile.setSource(dir);
}
```

Kotlin support in Gradle (as far as I can tell) is provided through a separate plugin, and there's therefore not a `KotlinSourceSet` type task in the Gradle Plugin API for us to use.

**Comment by jpenilla** [comment]
49f2e40be6b8f88cc09a9f0d8a492c59f68f2259

**Comment by DeflatedPickle** [comment]
Was this actually fixed? I've just put it in a project using the `buildscript` syntax;
```gradle
buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "net.kyori:blossom:$blossom_version"
    }
}
apply plugin: 'kotlin'
apply plugin: 'net.kyori.blossom'

blossom {
    replaceToken("£[id]", mod_name.toLowerCase())
}
```
Upon checking a built JAR from my project, I can see the tokens weren't replaced but according to IntelliJ, only `blossomSourceReplacementJava` is registered and it gets run before the Kotlin code has compiled

**Comment by jpenilla** [comment]
It should be fixed on master, but the latest release on the plugin portal (1.2.0) doesn't include those commits yet.

**Comment by DeflatedPickle** [comment]
Ah, my mistake. Sorry about that! Is there any way to use the development version?
