### ISSUE TITLE
Tokens are not being processed for Dokka pages

### ISSUE THREAD

**Issue by kikugie** [KyoriPowered/blossom#70]
For my project I have pages for both a written manual and generated code documentation. The code documentation is also available as javadoc, so I want to include links to the corresponding manual pages. 
I want to use blossom to be able to easily replace the links in case the manual structure changes:
```kotlin
sourceSets {
    fun TemplateSet.wiki(id: String, page: String, title: String = "Wiki page") {
        property("wiki-$id", "<a href=\"https://stonecutter.kikugie.dev/stonecutter/$page\">$title</a>")
    }

    main {
        blossom {
            kotlinSources {
                property("version", project.version.toString())
                wiki("eval", "guide/setup#checking-versions")
                wiki("chisel", "guide/setup#chiseled-tasks")
            }
        }
    }
}
```
And in the code I add
```
/**
 * (Description)
 * @see {{ wiki-eval }}
 */
```

However, the links are not being inserted in the rendered pages. Is there a solution for this?

**Comment by jpenilla** [comment]
Where is the file you are expecting replacements in located relative to the project root

**Comment by kikugie** [comment]
The source file is in `src/main/kotlin/dev/kikugie/stonecutter/StonecutterUtility.kt`

**Comment by jpenilla** [comment]
Template Kotlin sources go in `kotlin-templates`, not `kotlin`, similar to Java which is noted in the readme: https://github.com/KyoriPowered/blossom?tab=readme-ov-file#source-templating

Directly modifying source files is not compatible with the Gradle model, hence why v2 moved to a template system.

**Comment by zml2008** [comment]
Does dokka have some think like javadoc's taglets? That might be more along the lines of what you're trying to do.

**Comment by kikugie** [comment]
> Does dokka have some think like javadoc's taglets? That might be more along the lines of what you're trying to do.

I'm not aware of that, and unfortunately I can't put the code in `kotlin-templates`. For now I wrote a task I run manually to modify the source.
